apiVersion: v1
kind: Service
metadata:
    name: "maink8s-2aee"
    labels:
        app: "maink8s-2aee"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "maink8s-2aee"