on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: maink8sregistry.azurecr.io
        username: ${{ secrets.acr_maink8sregistry_username }}
        password: ${{ secrets.acr_maink8sregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/pythonapp" -f  "usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -t maink8sregistry.azurecr.io/maink8s:${{ github.sha }} --label dockerfile-path=usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        docker push maink8sregistry.azurecr.io/maink8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_maink8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pythonondocker | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pythonondocker`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pythonondocker
        container-registry-url: maink8sregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_maink8sregistry_username }}
        container-registry-password: ${{ secrets.acr_maink8sregistry_password }}
        secret-name: maink8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: pythonondocker
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          maink8sregistry.azurecr.io/maink8s:${{ github.sha }}
        imagepullsecrets: |
          maink8sdockerauth
